version: 2
jobs:
  test:
    docker:
      - image: golang:1.11.0
    working_directory: ~/go/src/github.com/user/api
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Run tests
          command: go test ./...